[project]
name = "python-final-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kss8014", email = "kss8014@daum.net" }
]
requires-python = ">=3.14"
dependencies = [
    "isbnlib>=3.10.14",
]

[project.scripts]
python-final-project = "python_final_project:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
